### ISSUE TITLE
unknown field auth error

### ISSUE THREAD

**Issue by kumaresh0** [justmiles/cq-source-crowdstrike#2]
unable to use [cq-source-crowdstrike](https://github.com/justmiles/cq-source-crowdstrike) plugin to fetch info, encountering this below error. Could you also please share info on how the siteurl format example?

config used 
```
kind: source
spec:
  name: "crowdstrike"
  registry: "github"
  path: "justmiles/crowdstrike"
  version: "v0.0.3"
  destinations: ["postgresql"]
  tables: ["*"]
  spec:
    auth:
      strategy: "ondemand"
      creds:
        siteUrl: https://falcon.crowdstrike.com/
        # align creds with the used strategy
```

error
`2023-06-21T09:35:33Z ERR finished call grpc.code=Unknown grpc.component=server grpc.error="failed to sync resources: failed to create execution client for source plugin justmiles-crowdstrike: failed to unmarshal plugin spec: json: unknown field \"auth\"" grpc.method=Sync grpc.method_type=server_stream grpc.service=cloudquery.source.v2.Source grpc.start_time=2023-06-21T18:35:33+09:00 grpc.time_ms=0.535 module=cli peer.address= protocol=grpc`
